version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dimon
      MONGO_INITDB_ROOT_PASSWORD: "12345"

    volumes:
      - ./mongodb/mongodb_data:/data/db
      - ./mongodb/mongodb_config:/data/configdb
    networks:
      - node-network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dimonabinsk
      ME_CONFIG_BASICAUTH_PASSWORD: di19772312mon
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: dimon
      ME_CONFIG_MONGODB_ADMINPASSWORD: "12345"
      ME_CONFIG_MONGODB_URL: mongodb://dimon:12345@mongo:27017/
    depends_on:
      - mongo
    networks:
      - node-network

  natours-app:
    build: ./api
    container_name: natours
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./api/:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE: mongodb://mongo:27017/
      USERNAME: dimon
      PASSWORD: "12345"
      JWT_SECRET: "this-super-secret-string-naturs-app"
      JWT_EXPIRES_IN: "90d"
    depends_on:
      - mongo
      - mongo-express
    networks:
      - node-network

networks:
  node-network:
    driver: bridge